preload = ["./typia-preload.ts"]

[test]
preload = ["./typia-preload.ts"]
coveragePathIgnorePatterns = [
  "**/*.spec.ts",
  "**/*.test.ts",
  "**/*.tsx",

  "src/theme/**",
  "src/*.ts",

  "*.config.ts",
  "*.config.js",
]
