#!/usr/bin/env bash
# Runs INSIDE the pinned opencascade.js image (Docker or chrooted rootfs), from /src.
# 1. Applies the hash-pinned raw_destructor generator patch.
# 2. Regenerates every recipe-bound precompiled base binding with the image's own
#    generator and accepts ONLY the removal of the placement-delete no-op
#    raw_destructor specialization for the expected classes.
# 3. Recompiles exactly the changed sources with compileBindings' own flags.
# 4. Hands off to the unchanged buildFromYaml.py.
set -euo pipefail
cd /src
patch_file=occ-binding-patches/opencascade-js-raw-destructor.patch
patch_sha256=f42b5f4f073dec635a5891203b4fac81ae7569efcb376932eb8fa3093de98dfd
bindings_before_sha256=2a9ccca339e74416d4605f0289bb0603502d1ce189eb370b66423765e81d5aac
bindings_after_sha256=b23f4dcb9f75eb86b55be00f4210aa8ca0999ded34b443ef4a43286db4008284
receipts=/src/binding-regeneration
[[ ${threading:-} == single-threaded ]] || { echo "Expected threading=single-threaded" >&2; exit 2; }
if [[ -e $receipts ]]; then echo "Refusing stale $receipts; prepare a new stage." >&2; exit 2; fi
mkdir "$receipts"

echo "=== generator patch ==="
printf '%s  %s\n' "$patch_sha256" "$patch_file" | sha256sum --check
printf '%s  %s\n' "$bindings_before_sha256" /opencascade.js/src/bindings.py | sha256sum --check
sha256sum /opencascade.js/src/bindings.py > "$receipts/bindings.py.before.sha256"
patch --forward --no-backup-if-mismatch -p1 -d /opencascade.js < "$patch_file"
printf '%s  %s\n' "$bindings_after_sha256" /opencascade.js/src/bindings.py | sha256sum --check
sha256sum /opencascade.js/src/bindings.py > "$receipts/bindings.py.after.sha256"
sha256sum /opencascade.js/src/generateBindings.py /opencascade.js/src/compileBindings.py \
  /opencascade.js/src/buildFromYaml.py > "$receipts/generator-scripts.sha256"

echo "=== regenerate recipe-bound base bindings ==="
RECIPE=$1 RECEIPTS=$receipts python3 - <<'PY'
import difflib, functools, hashlib, json, multiprocessing, os, re, shutil, sys, yaml
sys.path.insert(0, "/opencascade.js/src")
import generateBindings as g
import compileBindings as c

# Base classes whose v8 raw_destructor was a no-op solely because
# DEFINE_STANDARD_ALLOC declares a two-argument placement operator delete.
EXPECTED = set("""
gp_Vec2d gp_Vec gp_Trsf gp_Torus gp_Sphere gp_Pnt2d gp_Pnt gp_Pln gp_Lin gp_Dir2d
gp_Dir gp_Cylinder gp_Cone gp_Circ2d gp_Circ gp_Ax3 gp_Ax2d gp_Ax2 gp_Ax1 TopoDS_Wire
TopoDS_Vertex TopoDS_Solid TopoDS_Shell TopoDS_Shape TopoDS_Face TopoDS_Edge
TopoDS_Compound TopoDS_Builder TopoDS TopLoc_Location TopExp_Explorer TopExp
TNaming_Tool TNaming_Selector TNaming_Builder TDF_Label TCollection_ExtendedString
Standard_Transient STEPControl_Writer Poly_Triangle 
NCollection_BaseList IntRes2d_IntersectionSegment IntRes2d_IntersectionPoint
 IntAna2d_IntPoint IntAna2d_AnaIntersection Geom2dInt_GInter
GProp_GProps GC_Root GC_MakeCircle GC_MakeArcOfCircle BRepTools_WireExplorer BRepTools
BRepPrimAPI_MakeSweep BRepPrimAPI_MakeRevol BRepPrimAPI_MakePrism BRepPrimAPI_MakeOneAxis
BRepPrimAPI_MakeCylinder BRepPrimAPI_MakeBox BRepOffsetAPI_ThruSections
BRepOffsetAPI_MakeThickSolid BRepOffsetAPI_MakePipeShell BRepOffsetAPI_MakePipe
BRepOffsetAPI_MakeOffsetShape BRepOffsetAPI_DraftAngle BRepGProp BRepFilletAPI_MakeFillet
BRepFilletAPI_MakeChamfer BRepFilletAPI_LocalOperation BRepCheck_Analyzer
BRepBuilderAPI_Transform BRepBuilderAPI_NurbsConvert BRepBuilderAPI_ModifyShape
BRepBuilderAPI_MakeWire BRepBuilderAPI_MakeVertex BRepBuilderAPI_MakeSolid
BRepBuilderAPI_MakeShape BRepBuilderAPI_MakePolygon BRepBuilderAPI_MakeFace
BRepBuilderAPI_MakeEdge BRepBuilderAPI_Command BRepAlgoAPI_Splitter BRepAlgoAPI_Fuse
BRepAlgoAPI_Cut BRepAlgoAPI_Common BRepAlgoAPI_BuilderAlgo BRepAlgoAPI_BooleanOperation
 BRep_Tool BRep_Builder
""".split())
# Non-public destructors keep the no-op (they also declare DEFINE_STANDARD_ALLOC);
# these must be regenerated byte-identically.
RETAINED_NOP = {"BRepAlgoAPI_Algo", "CDM_Document", "IntRes2d_Intersection", "NCollection_BaseMap"}
assert len(EXPECTED) == 88 and not EXPECTED & RETAINED_NOP

receipts = os.environ["RECEIPTS"]
original_root = "/opencascade.js/build/bindings"
regenerated_build = "/tmp/cadara-regenerated-build"
regenerated_root = regenerated_build + "/bindings"
backup_root = "/tmp/cadara-original-bindings"
nop = lambda name: "namespace emscripten { namespace internal { template<> void raw_destructor<%s>(%s* ptr) { /* do nothing */ } } }\n" % (name, name)
sha = lambda path: hashlib.sha256(open(path, "rb").read()).hexdigest()

config = yaml.safe_load(open(os.environ["RECIPE"]))
symbols = sorted({b["symbol"] for b in config["mainBuild"]["bindings"]})
index = {}
for dirpath, _, filenames in os.walk(original_root):
  if dirpath.startswith(original_root + "/myMain.h"):
    continue
  for name in filenames:
    if name.endswith(".cpp"):
      index.setdefault(name[:-4], []).append(os.path.relpath(os.path.join(dirpath, name), original_root))
targets = {s: index[s] for s in symbols if s in index}
assert all(len(paths) == 1 for paths in targets.values()), "ambiguous binding sources"
targets = {s: paths[0] for s, paths in targets.items()}
unbound = [s for s in symbols if s not in targets]
# Recipe symbols without a precompiled source are the Cadara shims generated by buildFromYaml.
assert all(s.startswith("Cadara") for s in unbound), unbound
assert EXPECTED | RETAINED_NOP <= set(targets), sorted((EXPECTED | RETAINED_NOP) - set(targets))

# Regenerate into a separate tree with the (patched) image generator.
g.buildDirectory = regenerated_build
preamble = g.ocIncludeStatements + "\n" + g.referenceTypeTemplateDefs
only = lambda base: (lambda child, custom: child.spelling in targets and base(child, custom))
everything = range(0, 1 << 30)
g.processChildBatch("", g.allChildrenGenerator, "bindings", ".cpp", only(g.filterClasses), g.embindGenerationFuncClasses, g.typedefGenerator, g.templateTypedefGenerator, preamble, False, everything)
g.processChildBatch("", g.templateTypedefGenerator, "bindings", ".cpp", only(g.filterTemplates), g.embindGenerationFuncTemplates, g.typedefGenerator, g.templateTypedefGenerator, preamble, False, everything)
g.processChildBatch("", g.enumGenerator, "bindings", ".cpp", only(g.filterEnums), g.embindGenerationFuncEnums, g.typedefGenerator, g.templateTypedefGenerator, preamble, False, everything)

rows, changed, failures, diff = [], [], [], []
for symbol, rel in sorted(targets.items()):
  original, regenerated = os.path.join(original_root, rel), os.path.join(regenerated_root, rel)
  if not os.path.exists(regenerated):
    failures.append("not regenerated: " + rel)
    continue
  before, after = open(original).read(), open(regenerated).read()
  status = "identical"
  if before != after:
    status = "changed"
    changed.append(symbol)
    lines_before, lines_after = before.splitlines(True), after.splitlines(True)
    expected_after = [line for line in lines_before if line != nop(symbol)]
    if symbol not in EXPECTED or len(expected_after) != len(lines_before) - 1 or lines_after != expected_after:
      failures.append("unexpected generated diff: " + rel)
    diff.extend(difflib.unified_diff(lines_before, lines_after, "a/" + rel, "b/" + rel))
  elif symbol in RETAINED_NOP and nop(symbol) not in before:
    failures.append("non-public destructor no-op missing: " + rel)
  rows.append("\t".join([symbol, rel, sha(original), sha(regenerated), status]))
if set(changed) != EXPECTED:
  failures.append("changed set mismatch: missing=%s extra=%s" % (sorted(EXPECTED - set(changed)), sorted(set(changed) - EXPECTED)))
open(receipts + "/regenerated-sources.tsv", "w").write("symbol\tpath\toriginal_sha256\tregenerated_sha256\tstatus\n" + "\n".join(rows) + "\n")
open(receipts + "/generated-diff.patch", "w").write("".join(diff))
summary = {"recipeSymbols": len(symbols), "regenerated": len(rows), "changed": len(changed), "identical": len(rows) - len(changed), "shimSymbolsGeneratedByBuildFromYaml": unbound, "failures": failures}
json.dump(summary, open(receipts + "/regeneration-summary.json", "w"), indent=2)
print(json.dumps(summary))
if failures:
  sys.exit("Regeneration acceptance failed")

# Reproduction control: the image toolchain/flags must rebuild unchanged sources
# byte-identically in place, so recompiled objects differ only by source changes.
compile = functools.partial(c.buildOneFile, {"threading": os.environ["threading"]})
control_rows = []
for symbol in sorted(RETAINED_NOP):
  obj = os.path.join(original_root, targets[symbol]) + ".o"
  shutil.move(obj, obj + ".image")
  compile(obj[:-2])
  control_rows.append("\t".join([symbol, sha(obj + ".image"), sha(obj)]))
  identical = sha(obj + ".image") == sha(obj)
  shutil.move(obj + ".image", obj)
  if not identical:
    sys.exit("Unchanged source did not recompile byte-identically: " + obj)
open(receipts + "/compile-reproduction-control.tsv", "w").write("symbol\timage_sha256\trecompiled_sha256\n" + "\n".join(control_rows) + "\n")

# Replace only the changed sources and recompile them with compileBindings' flags.
compile_rows, items = [], []
for symbol in sorted(changed):
  rel = targets[symbol]
  source = os.path.join(original_root, rel)
  os.makedirs(os.path.dirname(os.path.join(backup_root, rel)), exist_ok=True)
  shutil.move(source, os.path.join(backup_root, rel))
  shutil.move(source + ".o", os.path.join(backup_root, rel) + ".o")
  shutil.copyfile(os.path.join(regenerated_root, rel), source)
  items.append(source)
with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as pool:
  pool.map(compile, items)
for symbol in sorted(changed):
  rel = targets[symbol]
  old, new = os.path.join(backup_root, rel) + ".o", os.path.join(original_root, rel) + ".o"
  if not os.path.exists(new) or sha(old) == sha(new):
    sys.exit("Recompiled object missing or unchanged: " + rel)
  compile_rows.append("\t".join([symbol, rel + ".o", sha(old), sha(new)]))
open(receipts + "/recompiled-objects.tsv", "w").write("symbol\tobject\toriginal_sha256\trecompiled_sha256\n" + "\n".join(compile_rows) + "\n")
print("Recompiled %d changed base bindings" % len(compile_rows))
PY
(cd "$receipts" && sha256sum bindings.py.before.sha256 bindings.py.after.sha256 generator-scripts.sha256 \
  regenerated-sources.tsv generated-diff.patch regeneration-summary.json compile-reproduction-control.tsv \
  recompiled-objects.tsv > receipts.sha256)

echo "=== unchanged buildFromYaml ==="
exec /opencascade.js/src/buildFromYaml.py "$@"
