export {
  add,
  cross,
  dot,
  magnitude,
  negate,
  normalize,
  scale,
  subtract,
  type Vec3,
} from "@/domain/modeling/occ/math";

export {
  createPlaneAxes,
  extractPlanarFaceData,
  getSignedDistanceToSketchPlane,
  mapSketchPointToWorld,
  mapWorldPointToSketch,
  toGpAx1,
  toGpAx3,
  toGpDir,
  toGpPlane,
  toGpPnt,
  toGpVec,
  toSketchPlaneFrameFromGpAx3,
  toSketchPlaneFrameFromGpPlane,
  toVec3FromGpPoint,
  type ExtractedPlanarFaceData,
  type OpenCascadePlaneAxes,
  type SketchPlaneFrameInput,
} from "@/domain/modeling/occ/planes";
